// main.js - ShopEasy e-commerce site
// Uses autoGeneratedProducts from products_data.js

const products = {};

// Build products index from autoGeneratedProducts data
autoGeneratedProducts.forEach(function(p) {
    var cat = p.category_en || 'OTHER';
    if (!products[cat]) products[cat] = [];
    products[cat].push({
        id: p.id,
        name: p.name || p.title,
        price: p.price || p.suggested_price,
        originalPrice: p.price_usd * 2.5 || p.suggested_price * 1.5,
        category: p.category || 'General',
        rating: p.rating || 4.5,
        reviews: p.review_count || 0,
        image: p.image_url || (p.images ? p.images[0] : ''),
        images: p.images || [p.image_url],
        description: p.description || '',
        features: p.features || p.tags || [],
        specs: p.specifications || {}
    });

    // Also add to a flat list by source
    var src = p.source || '1688';
    if (!products[src]) products[src] = [];
    products[src].push(products[cat][products[cat].length - 1]);
});

// Categories display mapping
var CATEGORY_NAMES = {
    'HOME & LIVING': 'Home Storage',
    'TECH & GADGETS': 'Tech Accessories',
    'KITCHEN & DINING': 'Kitchen Gadgets',
    'PETS': 'Pet Supplies',
    'OFFICE & STATIONERY': 'Stationery',
    'BEAUTY & PERSONAL': 'Beauty & Personal'
};

// Get product by ID
function getProductById(id) {
    for (var cat in products) {
        if (!products.hasOwnProperty(cat)) continue;
        for (var i = 0; i < products[cat].length; i++) {
            if (products[cat][i].id == id) return products[cat][i];
        }
    }
    return null;
}

// Get all products as flat array
function getAllProducts() {
    var all = [];
    for (var cat in products) {
        if (!products.hasOwnProperty(cat) || cat === 'amazon' || cat === 'aliexpress' || cat === 'temu') continue;
        for (var i = 0; i < products[cat].length; i++) {
            all.push(products[cat][i]);
        }
    }
    return all;
}
