// 1688一件代发商品数据 - 更新时间: 2026-06-11
// 数据来源: 1688.com 一件代发精选商品
var autoGeneratedProducts = [
  {
    "id": "1688_001",
    "source": "1688",
    "category": "家居收纳",
    "title": "可折叠收纳箱 家用大容量塑料储物箱 带盖衣服被子整理箱",
    "price_cny": 15.8,
    "price_usd": 2.19,
    "suggested_price": 9.99,
    "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop",
    "tags": [
      "收纳",
      "家居",
      "整理",
      "折叠"
    ],
    "description": "大容量可折叠收纳箱，家用衣物被子整理必备，节省空间",
    "name": "可折叠收纳箱 家用大容量塑料储物箱 带盖衣服被子整理箱",
    "price": 9.99,
    "images": [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.6,
    "review_count": 62,
    "reviews": 62,
    "features": [
      "收纳",
      "家居"
    ],
    "originalPrice": 12.49,
    "isNew": true,
    "isSale": true,
    "discount": 14
  },
  {
    "id": "1688_002",
    "source": "1688",
    "category": "家居收纳",
    "title": "桌面收纳盒 多功能化妆品文具整理盒 分区储物盒",
    "price_cny": 8.5,
    "price_usd": 1.18,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&h=600&fit=crop",
    "tags": [
      "桌面收纳",
      "化妆盒",
      "文具盒",
      "分区"
    ],
    "description": "多功能桌面收纳盒，分区设计，适合化妆品和文具整理",
    "name": "桌面收纳盒 多功能化妆品文具整理盒 分区储物盒",
    "price": 5.99,
    "images": [
      "https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.7,
    "review_count": 396,
    "reviews": 396,
    "features": [
      "桌面收纳",
      "化妆盒"
    ],
    "originalPrice": 6.89,
    "isNew": false,
    "isSale": true,
    "discount": 11
  },
  {
    "id": "1688_003",
    "source": "1688",
    "category": "家居收纳",
    "title": "真空压缩袋 衣物被子收纳袋 抽气式省空间旅行必备",
    "price_cny": 12.0,
    "price_usd": 1.66,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&h=600&fit=crop",
    "tags": [
      "真空压缩",
      "旅行",
      "收纳",
      "省空间"
    ],
    "description": "真空压缩袋，轻松压缩衣物被子，旅行收纳必备神器",
    "name": "真空压缩袋 衣物被子收纳袋 抽气式省空间旅行必备",
    "price": 7.99,
    "images": [
      "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.0,
    "review_count": 161,
    "reviews": 161,
    "features": [
      "真空压缩",
      "旅行"
    ],
    "originalPrice": 9.59,
    "isNew": false,
    "isSale": true,
    "discount": 10
  },
  {
    "id": "1688_004",
    "source": "1688",
    "category": "数码配件",
    "title": "蓝牙5.3无线耳机 降噪TWS耳机 运动跑步耳机 适用苹果安卓",
    "price_cny": 25.0,
    "price_usd": 3.46,
    "suggested_price": 14.99,
    "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
    "tags": [
      "蓝牙耳机",
      "TWS",
      "降噪",
      "运动"
    ],
    "description": "蓝牙5.3无线耳机，主动降噪，舒适佩戴，续航持久",
    "name": "蓝牙5.3无线耳机 降噪TWS耳机 运动跑步耳机 适用苹果安卓",
    "price": 14.99,
    "images": [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop"
    ],
    "category_en": "ELECTRONICS",
    "rating": 4.5,
    "review_count": 416,
    "reviews": 416,
    "features": [
      "蓝牙耳机",
      "TWS"
    ],
    "originalPrice": 19.49,
    "isNew": true,
    "isSale": true,
    "discount": 28
  },
  {
    "id": "1688_005",
    "source": "1688",
    "category": "数码配件",
    "title": "磁吸充电宝 20000mAh 快充移动电源 便携大容量 适用苹果华为",
    "price_cny": 35.0,
    "price_usd": 4.85,
    "suggested_price": 19.99,
    "image_url": "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop",
    "tags": [
      "充电宝",
      "磁吸",
      "快充",
      "移动电源"
    ],
    "description": "20000mAh磁吸充电宝，支持快充，便携大容量",
    "name": "磁吸充电宝 20000mAh 快充移动电源 便携大容量 适用苹果华为",
    "price": 19.99,
    "images": [
      "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop"
    ],
    "category_en": "ELECTRONICS",
    "rating": 4.3,
    "review_count": 495,
    "reviews": 495,
    "features": [
      "充电宝",
      "磁吸"
    ],
    "originalPrice": 22.99,
    "isNew": false,
    "isSale": true,
    "discount": 15
  },
  {
    "id": "1688_006",
    "source": "1688",
    "category": "数码配件",
    "title": "手机支架 桌面可调节铝合金支架 直播追剧神器",
    "price_cny": 9.9,
    "price_usd": 1.37,
    "suggested_price": 4.99,
    "image_url": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop",
    "tags": [
      "手机支架",
      "桌面",
      "铝合金",
      "直播"
    ],
    "description": "铝合金桌面手机支架，可调节角度，直播追剧必备",
    "name": "手机支架 桌面可调节铝合金支架 直播追剧神器",
    "price": 4.99,
    "images": [
      "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop"
    ],
    "category_en": "ELECTRONICS",
    "rating": 4.6,
    "review_count": 224,
    "reviews": 224,
    "features": [
      "手机支架",
      "桌面"
    ],
    "originalPrice": 6.24,
    "isNew": true,
    "isSale": true,
    "discount": 40
  },
  {
    "id": "1688_007",
    "source": "1688",
    "category": "厨房用品",
    "title": "多功能厨房剪刀 食物剪鸡骨剪 可拆卸易清洗",
    "price_cny": 13.5,
    "price_usd": 1.87,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&h=600&fit=crop",
    "tags": [
      "厨房剪刀",
      "多功能",
      "可拆卸",
      "不锈钢"
    ],
    "description": "多功能厨房剪刀，可拆卸设计，易清洗，剪鸡骨蔬菜水果",
    "name": "多功能厨房剪刀 食物剪鸡骨剪 可拆卸易清洗",
    "price": 7.99,
    "images": [
      "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.7,
    "review_count": 102,
    "reviews": 102,
    "features": [
      "厨房剪刀",
      "多功能"
    ],
    "originalPrice": 9.19,
    "isNew": false,
    "isSale": true,
    "discount": 21
  },
  {
    "id": "1688_008",
    "source": "1688",
    "category": "厨房用品",
    "title": "硅胶锅铲六件套 不粘锅专用厨具 耐高温厨房套装",
    "price_cny": 22.0,
    "price_usd": 3.05,
    "suggested_price": 12.99,
    "image_url": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop",
    "tags": [
      "硅胶锅铲",
      "六件套",
      "不粘锅",
      "厨具"
    ],
    "description": "耐高温硅胶锅铲六件套，不伤不粘锅涂层，厨房必备",
    "name": "硅胶锅铲六件套 不粘锅专用厨具 耐高温厨房套装",
    "price": 12.99,
    "images": [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.8,
    "review_count": 359,
    "reviews": 359,
    "features": [
      "硅胶锅铲",
      "六件套"
    ],
    "originalPrice": 16.24,
    "isNew": false,
    "isSale": true,
    "discount": 33
  },
  {
    "id": "1688_009",
    "source": "1688",
    "category": "厨房用品",
    "title": "玻璃油瓶 防漏自动开合厨房调味瓶 500ml",
    "price_cny": 8.8,
    "price_usd": 1.22,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1594671148411-8d8de4d68e49?w=600&h=600&fit=crop",
    "tags": [
      "玻璃油瓶",
      "防漏",
      "自动开合",
      "调味瓶"
    ],
    "description": "自动开合玻璃油瓶，防漏设计，厨房调味品收纳好帮手",
    "name": "玻璃油瓶 防漏自动开合厨房调味瓶 500ml",
    "price": 5.99,
    "images": [
      "https://images.unsplash.com/photo-1594671148411-8d8de4d68e49?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.4,
    "review_count": 113,
    "reviews": 113,
    "features": [
      "玻璃油瓶",
      "防漏"
    ],
    "originalPrice": 7.79,
    "isNew": true,
    "isSale": true,
    "discount": 19
  },
  {
    "id": "1688_010",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物狗窝 四季通用猫窝 可拆洗柔软宠物床",
    "price_cny": 28.0,
    "price_usd": 3.88,
    "suggested_price": 16.99,
    "image_url": "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&h=600&fit=crop",
    "tags": [
      "宠物窝",
      "狗窝",
      "猫窝",
      "可拆洗"
    ],
    "description": "柔软舒适宠物窝，四季通用，可拆洗设计",
    "name": "宠物狗窝 四季通用猫窝 可拆洗柔软宠物床",
    "price": 16.99,
    "images": [
      "https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&h=600&fit=crop"
    ],
    "category_en": "PET SUPPLIES",
    "rating": 4.7,
    "review_count": 366,
    "reviews": 366,
    "features": [
      "宠物窝",
      "狗窝"
    ],
    "originalPrice": 21.24,
    "isNew": false,
    "isSale": true,
    "discount": 32
  },
  {
    "id": "1688_011",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物饮水机 USB静音循环过滤水机 自动猫狗饮水器",
    "price_cny": 32.0,
    "price_usd": 4.43,
    "suggested_price": 19.99,
    "image_url": "https://images.unsplash.com/photo-1574144113084-b6f450cc5e0c?w=600&h=600&fit=crop",
    "tags": [
      "宠物饮水机",
      "静音",
      "循环过滤",
      "USB"
    ],
    "description": "静音循环过滤宠物饮水机，USB供电，让宠物爱上喝水",
    "name": "宠物饮水机 USB静音循环过滤水机 自动猫狗饮水器",
    "price": 19.99,
    "images": [
      "https://images.unsplash.com/photo-1574144113084-b6f450cc5e0c?w=600&h=600&fit=crop"
    ],
    "category_en": "PET SUPPLIES",
    "rating": 4.1,
    "review_count": 388,
    "reviews": 388,
    "features": [
      "宠物饮水机",
      "静音"
    ],
    "originalPrice": 23.99,
    "isNew": false,
    "isSale": true,
    "discount": 12
  },
  {
    "id": "1688_012",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物指甲剪 防划伤安全修剪器 猫狗通用修甲工具",
    "price_cny": 6.5,
    "price_usd": 0.9,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=600&fit=crop",
    "tags": [
      "宠物指甲剪",
      "安全",
      "防划伤",
      "修甲"
    ],
    "description": "安全防划伤宠物指甲剪，猫狗通用，修剪指甲轻松安全",
    "name": "宠物指甲剪 防划伤安全修剪器 猫狗通用修甲工具",
    "price": 3.99,
    "images": [
      "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=600&fit=crop"
    ],
    "category_en": "PET SUPPLIES",
    "rating": 4.8,
    "review_count": 493,
    "reviews": 493,
    "features": [
      "宠物指甲剪",
      "安全"
    ],
    "originalPrice": 4.59,
    "isNew": false,
    "isSale": true,
    "discount": 24
  },
  {
    "id": "1688_013",
    "source": "1688",
    "category": "文具办公",
    "title": "创意笔记本 A5加厚线圈本 学生商务日记本 方格横线内页",
    "price_cny": 6.0,
    "price_usd": 0.83,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=600&h=600&fit=crop",
    "tags": [
      "笔记本",
      "A5",
      "线圈本",
      "方格"
    ],
    "description": "A5加厚线圈笔记本，方格横线可选，商务学生通用",
    "name": "创意笔记本 A5加厚线圈本 学生商务日记本 方格横线内页",
    "price": 3.99,
    "images": [
      "https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=600&h=600&fit=crop"
    ],
    "category_en": "OFFICE",
    "rating": 4.6,
    "review_count": 236,
    "reviews": 236,
    "features": [
      "笔记本",
      "A5"
    ],
    "originalPrice": 4.79,
    "isNew": false,
    "isSale": true,
    "discount": 16
  },
  {
    "id": "1688_014",
    "source": "1688",
    "category": "文具办公",
    "title": "无线蓝牙键盘 超薄静音平板手机通用键盘 出差便携",
    "price_cny": 18.0,
    "price_usd": 2.49,
    "suggested_price": 9.99,
    "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop",
    "tags": [
      "蓝牙键盘",
      "超薄",
      "静音",
      "便携"
    ],
    "description": "超薄静音蓝牙键盘，平板手机通用，出差办公便携神器",
    "name": "无线蓝牙键盘 超薄静音平板手机通用键盘 出差便携",
    "price": 9.99,
    "images": [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&h=600&fit=crop"
    ],
    "category_en": "OFFICE",
    "rating": 4.6,
    "review_count": 409,
    "reviews": 409,
    "features": [
      "蓝牙键盘",
      "超薄"
    ],
    "originalPrice": 11.49,
    "isNew": false,
    "isSale": true,
    "discount": 15
  },
  {
    "id": "1688_015",
    "source": "1688",
    "category": "文具办公",
    "title": "桌面书架 简约多层置物架 学生书桌收纳架",
    "price_cny": 15.0,
    "price_usd": 2.08,
    "suggested_price": 8.99,
    "image_url": "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=600&fit=crop",
    "tags": [
      "书架",
      "桌面",
      "收纳",
      "置物架"
    ],
    "description": "简约多层桌面书架，学生书桌收纳整理好物",
    "name": "桌面书架 简约多层置物架 学生书桌收纳架",
    "price": 8.99,
    "images": [
      "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&h=600&fit=crop"
    ],
    "category_en": "OFFICE",
    "rating": 4.5,
    "review_count": 175,
    "reviews": 175,
    "features": [
      "书架",
      "桌面"
    ],
    "originalPrice": 10.79,
    "isNew": false,
    "isSale": true,
    "discount": 18
  },
  {
    "id": "1688_016",
    "source": "1688",
    "category": "个护美妆",
    "title": "电动洗脸刷 硅胶洁面仪 深层清洁毛孔 防水USB充电",
    "price_cny": 16.5,
    "price_usd": 2.28,
    "suggested_price": 9.99,
    "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop",
    "tags": [
      "洗脸刷",
      "电动",
      "洁面仪",
      "硅胶"
    ],
    "description": "硅胶电动洗脸刷，深层清洁毛孔，防水USB充电",
    "name": "电动洗脸刷 硅胶洁面仪 深层清洁毛孔 防水USB充电",
    "price": 9.99,
    "images": [
      "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&h=600&fit=crop"
    ],
    "category_en": "HEALTH & BEAUTY",
    "rating": 4.9,
    "review_count": 377,
    "reviews": 377,
    "features": [
      "洗脸刷",
      "电动"
    ],
    "originalPrice": 11.99,
    "isNew": false,
    "isSale": true,
    "discount": 36
  },
  {
    "id": "1688_017",
    "source": "1688",
    "category": "个护美妆",
    "title": "便携冲牙器 水牙线 口腔清洁器 USB充电 洗牙神器",
    "price_cny": 22.0,
    "price_usd": 3.05,
    "suggested_price": 13.99,
    "image_url": "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=600&fit=crop",
    "tags": [
      "冲牙器",
      "水牙线",
      "口腔清洁",
      "便携"
    ],
    "description": "便携式冲牙器，深层清洁牙齿缝隙，USB充电",
    "name": "便携冲牙器 水牙线 口腔清洁器 USB充电 洗牙神器",
    "price": 13.99,
    "images": [
      "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&h=600&fit=crop"
    ],
    "category_en": "HEALTH & BEAUTY",
    "rating": 4.7,
    "review_count": 78,
    "reviews": 78,
    "features": [
      "冲牙器",
      "水牙线"
    ],
    "originalPrice": 16.79,
    "isNew": false,
    "isSale": true,
    "discount": 35
  },
  {
    "id": "1688_018",
    "source": "1688",
    "category": "个护美妆",
    "title": "防晒冰袖 男女开车骑行防晒套袖 冰丝透气UPF50+",
    "price_cny": 3.5,
    "price_usd": 0.48,
    "suggested_price": 2.99,
    "image_url": "https://images.unsplash.com/photo-1527011046414-4781f1e5f1c5?w=600&h=600&fit=crop",
    "tags": [
      "防晒",
      "冰袖",
      "开车",
      "骑行"
    ],
    "description": "UPF50+冰丝防晒冰袖，男女通用，开车骑行必备",
    "name": "防晒冰袖 男女开车骑行防晒套袖 冰丝透气UPF50+",
    "price": 2.99,
    "images": [
      "https://images.unsplash.com/photo-1527011046414-4781f1e5f1c5?w=600&h=600&fit=crop"
    ],
    "category_en": "HEALTH & BEAUTY",
    "rating": 4.3,
    "review_count": 187,
    "reviews": 187,
    "features": [
      "防晒",
      "冰袖"
    ],
    "originalPrice": 3.44,
    "isNew": true,
    "isSale": true,
    "discount": 40
  },
  {
    "id": "1688_019",
    "source": "1688",
    "category": "家居收纳",
    "title": "衣柜分层隔板 免打孔衣柜收纳架 伸缩置物架",
    "price_cny": 14.0,
    "price_usd": 1.94,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&h=600&fit=crop",
    "tags": [
      "衣柜分层",
      "免打孔",
      "收纳架",
      "伸缩"
    ],
    "description": "免打孔衣柜分层隔板，伸缩设计，充分利用衣柜空间",
    "name": "衣柜分层隔板 免打孔衣柜收纳架 伸缩置物架",
    "price": 7.99,
    "images": [
      "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.5,
    "review_count": 417,
    "reviews": 417,
    "features": [
      "衣柜分层",
      "免打孔"
    ],
    "originalPrice": 9.99,
    "isNew": true,
    "isSale": true,
    "discount": 25
  },
  {
    "id": "1688_020",
    "source": "1688",
    "category": "数码配件",
    "title": "Type-C数据线 6A快充 100W闪充 适用苹果安卓通用",
    "price_cny": 5.0,
    "price_usd": 0.69,
    "suggested_price": 2.99,
    "image_url": "https://images.unsplash.com/photo-1543881586-963e80405054?w=600&h=600&fit=crop",
    "tags": [
      "数据线",
      "Type-C",
      "快充",
      "闪充"
    ],
    "description": "6A大电流Type-C数据线，100W快充，通用兼容",
    "name": "Type-C数据线 6A快充 100W闪充 适用苹果安卓通用",
    "price": 2.99,
    "images": [
      "https://images.unsplash.com/photo-1543881586-963e80405054?w=600&h=600&fit=crop"
    ],
    "category_en": "ELECTRONICS",
    "rating": 4.4,
    "review_count": 379,
    "reviews": 379,
    "features": [
      "数据线",
      "Type-C"
    ],
    "originalPrice": 3.89,
    "isNew": true,
    "isSale": true,
    "discount": 14
  },
  {
    "id": "1688_021",
    "source": "1688",
    "category": "厨房用品",
    "title": "保鲜盒套装 冰箱收纳盒 食品级塑料密封盒 微波炉适用",
    "price_cny": 10.0,
    "price_usd": 1.38,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1588953936179-d2a8a60f0e78?w=600&h=600&fit=crop",
    "tags": [
      "保鲜盒",
      "冰箱收纳",
      "食品级",
      "密封"
    ],
    "description": "食品级密封保鲜盒套装，大中小三件，微波炉冰箱适用",
    "name": "保鲜盒套装 冰箱收纳盒 食品级塑料密封盒 微波炉适用",
    "price": 5.99,
    "images": [
      "https://images.unsplash.com/photo-1588953936179-d2a8a60f0e78?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.2,
    "review_count": 337,
    "reviews": 337,
    "features": [
      "保鲜盒",
      "冰箱收纳"
    ],
    "originalPrice": 7.49,
    "isNew": false,
    "isSale": true,
    "discount": 23
  },
  {
    "id": "1688_022",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物玩具球 发声耐咬狗狗玩具 磨牙解闷互动球",
    "price_cny": 3.0,
    "price_usd": 0.42,
    "suggested_price": 1.99,
    "image_url": "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&h=600&fit=crop",
    "tags": [
      "宠物玩具",
      "发声球",
      "耐咬",
      "磨牙"
    ],
    "description": "发声耐咬宠物玩具球，狗狗最爱，磨牙解闷互动好物",
    "name": "宠物玩具球 发声耐咬狗狗玩具 磨牙解闷互动球",
    "price": 1.99,
    "images": [
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&h=600&fit=crop"
    ],
    "category_en": "PET SUPPLIES",
    "rating": 4.8,
    "review_count": 254,
    "reviews": 254,
    "features": [
      "宠物玩具",
      "发声球"
    ],
    "originalPrice": 2.49,
    "isNew": true,
    "isSale": true,
    "discount": 14
  },
  {
    "id": "1688_023",
    "source": "1688",
    "category": "文具办公",
    "title": "多功能计算器 大屏幕办公商务用 太阳能双电源",
    "price_cny": 8.0,
    "price_usd": 1.11,
    "suggested_price": 4.99,
    "image_url": "https://images.unsplash.com/photo-1531746790095-e5cb15709714?w=600&h=600&fit=crop",
    "tags": [
      "计算器",
      "大屏幕",
      "太阳能",
      "办公"
    ],
    "description": "太阳能双电源多功能计算器，大屏幕显示，商务办公必备",
    "name": "多功能计算器 大屏幕办公商务用 太阳能双电源",
    "price": 4.99,
    "images": [
      "https://images.unsplash.com/photo-1531746790095-e5cb15709714?w=600&h=600&fit=crop"
    ],
    "category_en": "OFFICE",
    "rating": 4.5,
    "review_count": 96,
    "reviews": 96,
    "features": [
      "计算器",
      "大屏幕"
    ],
    "originalPrice": 5.74,
    "isNew": false,
    "isSale": true,
    "discount": 14
  },
  {
    "id": "1688_024",
    "source": "1688",
    "category": "个护美妆",
    "title": "男士电动剃须刀 全身水洗 干湿双剃 便携充电刮胡刀",
    "price_cny": 18.0,
    "price_usd": 2.49,
    "suggested_price": 11.99,
    "image_url": "https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&h=600&fit=crop",
    "tags": [
      "剃须刀",
      "电动",
      "水洗",
      "便携"
    ],
    "description": "全身水洗电动剃须刀，干湿双剃，便携充电",
    "name": "男士电动剃须刀 全身水洗 干湿双剃 便携充电刮胡刀",
    "price": 11.99,
    "images": [
      "https://images.unsplash.com/photo-1621607512214-68297480165e?w=600&h=600&fit=crop"
    ],
    "category_en": "HEALTH & BEAUTY",
    "rating": 4.6,
    "review_count": 455,
    "reviews": 455,
    "features": [
      "剃须刀",
      "电动"
    ],
    "originalPrice": 15.59,
    "isNew": false,
    "isSale": true,
    "discount": 22
  },
  {
    "id": "1688_025",
    "source": "1688",
    "category": "家居收纳",
    "title": "墙壁挂壁收纳架 免打孔浴室厨房置物架 无痕贴",
    "price_cny": 5.5,
    "price_usd": 0.76,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
    "tags": [
      "挂壁",
      "免打孔",
      "置物架",
      "浴室"
    ],
    "description": "免打孔墙壁置物架，无痕粘贴，浴室厨房收纳节省空间",
    "name": "墙壁挂壁收纳架 免打孔浴室厨房置物架 无痕贴",
    "price": 3.99,
    "images": [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.3,
    "review_count": 289,
    "reviews": 289,
    "features": [
      "挂壁",
      "免打孔"
    ],
    "originalPrice": 4.99,
    "isNew": false,
    "isSale": true,
    "discount": 37
  },
  {
    "id": "1688_026",
    "source": "1688",
    "category": "数码配件",
    "title": "USB小夜灯 感应人体自动开关 床头起夜灯 插电式",
    "price_cny": 7.0,
    "price_usd": 0.97,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&h=600&fit=crop",
    "tags": [
      "小夜灯",
      "感应",
      "USB",
      "床头"
    ],
    "description": "人体感应USB小夜灯，自动开关，柔和光线不刺眼",
    "name": "USB小夜灯 感应人体自动开关 床头起夜灯 插电式",
    "price": 3.99,
    "images": [
      "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&h=600&fit=crop"
    ],
    "category_en": "ELECTRONICS",
    "rating": 4.8,
    "review_count": 398,
    "reviews": 398,
    "features": [
      "小夜灯",
      "感应"
    ],
    "originalPrice": 4.59,
    "isNew": false,
    "isSale": true,
    "discount": 27
  },
  {
    "id": "1688_027",
    "source": "1688",
    "category": "厨房用品",
    "title": "厨房油壶 自动开合防漏 调料瓶油瓶 玻璃材质",
    "price_cny": 7.5,
    "price_usd": 1.04,
    "suggested_price": 4.99,
    "image_url": "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&h=600&fit=crop",
    "tags": [
      "油壶",
      "防漏",
      "玻璃",
      "自动开合"
    ],
    "description": "自动开合防漏厨房油壶，玻璃瓶身，重力开盖设计",
    "name": "厨房油壶 自动开合防漏 调料瓶油瓶 玻璃材质",
    "price": 4.99,
    "images": [
      "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&h=600&fit=crop"
    ],
    "category_en": "HOME & LIVING",
    "rating": 4.7,
    "review_count": 443,
    "reviews": 443,
    "features": [
      "油壶",
      "防漏"
    ],
    "originalPrice": 6.24,
    "isNew": true,
    "isSale": true,
    "discount": 23
  },
  {
    "id": "1688_028",
    "source": "1688",
    "category": "宠物用品",
    "title": "猫咪梳子 去毛神器 宠物除毛刷 狗狗猫用脱毛梳",
    "price_cny": 4.5,
    "price_usd": 0.62,
    "suggested_price": 2.99,
    "image_url": "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=600&fit=crop",
    "tags": [
      "宠物梳",
      "去毛",
      "除毛刷",
      "猫咪"
    ],
    "description": "高效去毛宠物梳，轻松梳理脱落毛发，猫狗通用",
    "name": "猫咪梳子 去毛神器 宠物除毛刷 狗狗猫用脱毛梳",
    "price": 2.99,
    "images": [
      "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=600&fit=crop"
    ],
    "category_en": "PET SUPPLIES",
    "rating": 4.1,
    "review_count": 51,
    "reviews": 51,
    "features": [
      "宠物梳",
      "去毛"
    ],
    "originalPrice": 3.74,
    "isNew": false,
    "isSale": true,
    "discount": 34
  },
  {
    "id": "1688_029",
    "source": "1688",
    "category": "文具办公",
    "title": "鼠标垫 大号护腕 游戏办公桌垫 防水PU皮革",
    "price_cny": 5.0,
    "price_usd": 0.69,
    "suggested_price": 2.99,
    "image_url": "https://images.unsplash.com/photo-1629429407759-01cd3d7cfb7b?w=600&h=600&fit=crop",
    "tags": [
      "鼠标垫",
      "护腕",
      "大号",
      "PU皮革"
    ],
    "description": "大号护腕鼠标垫，PU皮革防水材质，游戏办公通用",
    "name": "鼠标垫 大号护腕 游戏办公桌垫 防水PU皮革",
    "price": 2.99,
    "images": [
      "https://images.unsplash.com/photo-1629429407759-01cd3d7cfb7b?w=600&h=600&fit=crop"
    ],
    "category_en": "OFFICE",
    "rating": 4.2,
    "review_count": 104,
    "reviews": 104,
    "features": [
      "鼠标垫",
      "护腕"
    ],
    "originalPrice": 3.74,
    "isNew": false,
    "isSale": true,
    "discount": 26
  },
  {
    "id": "1688_030",
    "source": "1688",
    "category": "个护美妆",
    "title": "头发干洗喷雾 免洗蓬松去油 便携控油蓬松粉",
    "price_cny": 6.0,
    "price_usd": 0.83,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&h=600&fit=crop",
    "tags": [
      "干洗喷雾",
      "免洗",
      "蓬松",
      "控油"
    ],
    "description": "免洗头发干洗喷雾，快速去油蓬松，便携随身",
    "name": "头发干洗喷雾 免洗蓬松去油 便携控油蓬松粉",
    "price": 3.99,
    "images": [
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&h=600&fit=crop"
    ],
    "category_en": "HEALTH & BEAUTY",
    "rating": 4.5,
    "review_count": 128,
    "reviews": 128,
    "features": [
      "干洗喷雾",
      "免洗"
    ],
    "originalPrice": 4.99,
    "isNew": false,
    "isSale": true,
    "discount": 27
  }
];
