// 1688一件代发商品数据 - 更新时间: 2026-06-11
// 数据来源: 1688.com 一件代发精选商品
const autoGeneratedProducts = [

  {
    "id": "1688_001",
    "source": "1688",
    "category": "家居收纳",
    "title": "可折叠收纳箱 家用大容量塑料储物箱 带盖衣服被子整理箱",
    "price_cny": 15.8,
    "price_usd": 2.19,
    "suggested_price": 9.99,
    "image_url": "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=600&fit=crop",
    "tags": ["收纳", "家居", "整理", "折叠"],
    "description": "大容量可折叠收纳箱，家用衣物被子整理必备，节省空间"
  },

  {
    "id": "1688_002",
    "source": "1688",
    "category": "家居收纳",
    "title": "桌面收纳盒 多功能化妆品文具整理盒 分区储物盒",
    "price_cny": 8.5,
    "price_usd": 1.18,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1544457070-4cd773b4d71e?w=600&h=600&fit=crop",
    "tags": ["桌面收纳", "化妆盒", "文具盒", "分区"],
    "description": "多功能桌面收纳盒，分区设计，适合化妆品和文具整理"
  },

  {
    "id": "1688_003",
    "source": "1688",
    "category": "家居收纳",
    "title": "真空压缩袋 衣物被子收纳袋 抽气式省空间旅行必备",
    "price_cny": 12.0,
    "price_usd": 1.66,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&h=600&fit=crop",
    "tags": ["真空压缩", "旅行", "收纳", "省空间"],
    "description": "真空压缩袋，轻松压缩衣物被子，旅行收纳必备神器"
  },

  {
    "id": "1688_004",
    "source": "1688",
    "category": "数码配件",
    "title": "蓝牙5.3无线耳机 降噪TWS耳机 运动跑步耳机 适用苹果安卓",
    "price_cny": 25.0,
    "price_usd": 3.46,
    "suggested_price": 14.99,
    "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop",
    "tags": ["蓝牙耳机", "TWS", "降噪", "运动"],
    "description": "蓝牙5.3无线耳机，主动降噪，舒适佩戴，续航持久"
  },

  {
    "id": "1688_005",
    "source": "1688",
    "category": "数码配件",
    "title": "快充数据线 三合一充电线 苹果Type-C安卓通用 1.2米",
    "price_cny": 6.8,
    "price_usd": 0.94,
    "suggested_price": 4.99,
    "image_url": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop",
    "tags": ["数据线", "快充", "三合一", "通用"],
    "description": "三合一快充数据线，苹果Type-C安卓全兼容，1.2米长度"
  },

  {
    "id": "1688_006",
    "source": "1688",
    "category": "数码配件",
    "title": "手机支架 桌面可调节 直播支架 平板通用 铝合金材质",
    "price_cny": 9.9,
    "price_usd": 1.37,
    "suggested_price": 6.99,
    "image_url": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop",
    "tags": ["手机支架", "桌面", "直播", "可调节"],
    "description": "铝合金手机支架，多角度可调节，直播追剧必备"
  },

  {
    "id": "1688_007",
    "source": "1688",
    "category": "数码配件",
    "title": "无线充电器 15W快充 手机无线充电板 兼容苹果三星华为",
    "price_cny": 18.0,
    "price_usd": 2.49,
    "suggested_price": 11.99,
    "image_url": "https://images.unsplash.com/photo-1586816001966-79b736744398?w=600&h=600&fit=crop",
    "tags": ["无线充电", "快充", "充电板", "通用"],
    "description": "15W无线快充充电器，兼容主流手机品牌，轻薄便携"
  },

  {
    "id": "1688_008",
    "source": "1688",
    "category": "厨房用品",
    "title": "硅胶锅铲套装 不粘锅专用 耐高温厨房烹饪工具5件套",
    "price_cny": 19.9,
    "price_usd": 2.76,
    "suggested_price": 12.99,
    "image_url": "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop",
    "tags": ["锅铲", "硅胶", "不粘锅", "厨房工具"],
    "description": "耐高温硅胶锅铲5件套，不伤不粘锅涂层，厨房必备"
  },

  {
    "id": "1688_009",
    "source": "1688",
    "category": "厨房用品",
    "title": "切菜神器 多功能蔬菜切片切丝器 厨房料理工具 护手设计",
    "price_cny": 14.5,
    "price_usd": 2.01,
    "suggested_price": 8.99,
    "image_url": "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=600&h=600&fit=crop",
    "tags": ["切菜器", "厨房", "切片", "切丝", "护手"],
    "description": "多功能切菜神器，切片切丝轻松搞定，护手设计安全放心"
  },

  {
    "id": "1688_010",
    "source": "1688",
    "category": "厨房用品",
    "title": "密封玻璃罐 厨房收纳罐 五谷杂粮干果储物罐 500ml",
    "price_cny": 5.5,
    "price_usd": 0.76,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1578500494198-246f612d3b3d?w=600&h=600&fit=crop",
    "tags": ["密封罐", "玻璃", "厨房收纳", "杂粮"],
    "description": "密封玻璃储物罐，防潮防虫，适合五谷杂粮干果保存"
  },

  {
    "id": "1688_011",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物玩具球 狗狗耐咬发声球 橡胶磨牙玩具 中型犬",
    "price_cny": 9.0,
    "price_usd": 1.25,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1571566882372-1598d88d90b8?w=600&h=600&fit=crop",
    "tags": ["宠物", "狗玩具", "发声球", "耐咬"],
    "description": "耐咬发声宠物玩具球，橡胶材质，狗狗磨牙解闷必备"
  },

  {
    "id": "1688_012",
    "source": "1688",
    "category": "宠物用品",
    "title": "猫抓板 瓦楞纸猫窝 磨爪玩具 可躺可抓 猫咪用品",
    "price_cny": 12.0,
    "price_usd": 1.66,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&h=600&fit=crop",
    "tags": ["猫咪", "猫抓板", "猫窝", "磨爪"],
    "description": "瓦楞纸猫抓板猫窝二合一，可躺可抓，猫咪最爱"
  },

  {
    "id": "1688_013",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物自动喂食器 定时定量 猫狗通用 3L容量",
    "price_cny": 68.0,
    "price_usd": 9.42,
    "suggested_price": 29.99,
    "image_url": "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=600&fit=crop",
    "tags": ["宠物", "自动喂食器", "定时", "猫狗"],
    "description": "智能定时定量自动喂食器，出差旅行宠物喂食无忧"
  },

  {
    "id": "1688_014",
    "source": "1688",
    "category": "文具办公",
    "title": "创意笔记本 A5加厚空白本 简约皮面手帐日记本 160页",
    "price_cny": 7.5,
    "price_usd": 1.04,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1531347561265-3bf1c171108d?w=600&h=600&fit=crop",
    "tags": ["笔记本", "手帐", "文具", "创意"],
    "description": "A5加厚创意笔记本，皮质封面，160页空白内页"
  },

  {
    "id": "1688_015",
    "source": "1688",
    "category": "文具办公",
    "title": "桌面吸尘器 迷你键盘清洁 橡皮屑收集 学生办公神器",
    "price_cny": 16.8,
    "price_usd": 2.33,
    "suggested_price": 9.99,
    "image_url": "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=600&fit=crop",
    "tags": ["桌面清洁", "吸尘器", "办公", "学生"],
    "description": "迷你桌面吸尘器，轻松清理键盘缝隙和橡皮屑，办公学习必备"
  },

  {
    "id": "1688_016",
    "source": "1688",
    "category": "文具办公",
    "title": "多功能笔筒 创意桌面收纳 办公文具笔架 旋转设计",
    "price_cny": 10.0,
    "price_usd": 1.38,
    "suggested_price": 6.99,
    "image_url": "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&h=600&fit=crop",
    "tags": ["笔筒", "桌面收纳", "办公", "旋转"],
    "description": "旋转多功能笔筒，大容量桌面文具收纳，办公桌整洁神器"
  },

  {
    "id": "1688_017",
    "source": "1688",
    "category": "个护美妆",
    "title": "化妆刷套装 12支专业化妆刷 初学者化妆品工具 柔软刷毛",
    "price_cny": 22.0,
    "price_usd": 3.05,
    "suggested_price": 13.99,
    "image_url": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=600&fit=crop",
    "tags": ["化妆刷", "美妆工具", "初学者", "套装"],
    "description": "12支专业化妆刷套装，柔软刷毛，初学者入门首选"
  },

  {
    "id": "1688_018",
    "source": "1688",
    "category": "个护美妆",
    "title": "便携化妆镜 LED补光 双面放大 随身携带 充电款",
    "price_cny": 15.0,
    "price_usd": 2.08,
    "suggested_price": 9.99,
    "image_url": "https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=600&h=600&fit=crop",
    "tags": ["化妆镜", "LED", "补光", "便携"],
    "description": "LED补光化妆镜，双面放大，充电便携，随时随地补妆"
  },

  {
    "id": "1688_019",
    "source": "1688",
    "category": "个护美妆",
    "title": "面膜收纳盒 透明翻盖 可放50片 桌面护肤品整理盒",
    "price_cny": 11.0,
    "price_usd": 1.52,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
    "tags": ["面膜盒", "护肤品收纳", "透明", "整理"],
    "description": "大容量面膜收纳盒，透明翻盖设计，可存放50片面膜"
  },

  {
    "id": "1688_020",
    "source": "1688",
    "category": "家居收纳",
    "title": "墙壁置物架 免打孔 浴室厨房收纳架 太空铝材质",
    "price_cny": 16.0,
    "price_usd": 2.22,
    "suggested_price": 10.99,
    "image_url": "https://images.unsplash.com/photo-1558704164-ab7a0016c1f3?w=600&h=600&fit=crop",
    "tags": ["置物架", "免打孔", "浴室", "厨房", "收纳"],
    "description": "免打孔墙壁置物架，太空铝材质，浴室厨房收纳省空间"
  },

  {
    "id": "1688_021",
    "source": "1688",
    "category": "家居收纳",
    "title": "衣柜分层隔板 伸缩收纳架 免钉宿舍衣柜置物架 60cm",
    "price_cny": 18.0,
    "price_usd": 2.49,
    "suggested_price": 11.99,
    "image_url": "https://images.unsplash.com/photo-1597006335776-25a2c72b1d30?w=600&h=600&fit=crop",
    "tags": ["衣柜", "分层架", "隔板", "收纳", "免钉"],
    "description": "免钉衣柜分层隔板，伸缩设计，衣柜空间利用率翻倍"
  },

  {
    "id": "1688_022",
    "source": "1688",
    "category": "数码配件",
    "title": "手机挂绳 十字链 防摔吊绳 适用苹果安卓 多色可选",
    "price_cny": 3.5,
    "price_usd": 0.48,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&h=600&fit=crop",
    "tags": ["手机挂绳", "防摔", "吊绳", "配件"],
    "description": "时尚手机挂绳，防摔设计，多色可选，解放双手"
  },

  {
    "id": "1688_023",
    "source": "1688",
    "category": "厨房用品",
    "title": "厨房计时器 机械定时器 闹钟 厨房小工具 可爱造型",
    "price_cny": 6.0,
    "price_usd": 0.83,
    "suggested_price": 4.99,
    "image_url": "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&h=600&fit=crop",
    "tags": ["计时器", "厨房", "闹钟", "定时"],
    "description": "机械厨房计时器，可爱造型，无需电池，精准定时"
  },

  {
    "id": "1688_024",
    "source": "1688",
    "category": "宠物用品",
    "title": "宠物梳子 狗狗去底绒梳 猫狗通用 除毛梳 顺毛神器",
    "price_cny": 8.0,
    "price_usd": 1.11,
    "suggested_price": 5.99,
    "image_url": "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&h=600&fit=crop",
    "tags": ["宠物梳", "除毛", "猫狗", "顺毛"],
    "description": "宠物去底绒梳，猫狗通用，轻松打理宠物毛发"
  },

  {
    "id": "1688_025",
    "source": "1688",
    "category": "文具办公",
    "title": "便签纸 创意Memo贴 备忘录 彩色便签条 100张/包",
    "price_cny": 2.5,
    "price_usd": 0.35,
    "suggested_price": 2.99,
    "image_url": "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&h=600&fit=crop",
    "tags": ["便签", "Memo", "办公", "文具"],
    "description": "创意彩色便签条，100张/包，办公学习备忘好帮手"
  },

  {
    "id": "1688_026",
    "source": "1688",
    "category": "个护美妆",
    "title": "洗脸发带 可爱吸水毛巾发箍 化妆洗面奶必备 加厚款",
    "price_cny": 4.0,
    "price_usd": 0.55,
    "suggested_price": 3.99,
    "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=600&fit=crop",
    "tags": ["发带", "洗脸", "毛巾", "化妆"],
    "description": "加厚吸水洗脸发带，可爱造型，化妆洗脸必备"
  },

  {
    "id": "1688_027",
    "source": "1688",
    "category": "厨房用品",
    "title": "保鲜盒套装 微波炉适用 冰箱收纳 食品级塑料 3件套",
    "price_cny": 12.0,
    "price_usd": 1.66,
    "suggested_price": 8.99,
    "image_url": "https://images.unsplash.com/photo-1558729143-ba3ef9e83e07?w=600&h=600&fit=crop",
    "tags": ["保鲜盒", "冰箱收纳", "微波炉", "食品级"],
    "description": "食品级塑料保鲜盒3件套，微波炉适用，冰箱收纳好帮手"
  },

  {
    "id": "1688_028",
    "source": "1688",
    "category": "家居收纳",
    "title": "S型挂钩 不锈钢 免打孔 浴室厨房 多用挂钩 10个装",
    "price_cny": 3.0,
    "price_usd": 0.42,
    "suggested_price": 2.99,
    "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=600&fit=crop",
    "tags": ["挂钩", "S型", "不锈钢", "免打孔"],
    "description": "不锈钢S型挂钩10个装，免打孔安装，浴室厨房通用"
  },

  {
    "id": "1688_029",
    "source": "1688",
    "category": "数码配件",
    "title": "USB小夜灯 护眼床头灯 智能感应 可充电 温馨卧室灯",
    "price_cny": 11.0,
    "price_usd": 1.52,
    "suggested_price": 7.99,
    "image_url": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=600&h=600&fit=crop",
    "tags": ["小夜灯", "USB", "护眼", "感应", "卧室"],
    "description": "USB充电智能感应小夜灯，护眼柔光，卧室床头温馨必备"
  },

  {
    "id": "1688_030",
    "source": "1688",
    "category": "家居收纳",
    "title": "鞋架 家用门口简易鞋柜 多层防尘 收纳神器 可定制",
    "price_cny": 25.0,
    "price_usd": 3.46,
    "suggested_price": 15.99,
    "image_url": "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&h=600&fit=crop",
    "tags": ["鞋架", "收纳", "门口", "多层"],
    "description": "简易多层鞋架，门口玄关收纳，防尘实用，节省空间"
  },

];

// 合并到现有产品数据
if (typeof products !== 'undefined') {
    const existingProductIds = new Set(products.map(p => p.id));
    const newProducts = autoGeneratedProducts.filter(p => !existingProductIds.has(p.id));
    products = [...products, ...newProducts];
} else {
    var products = autoGeneratedProducts;
}

console.log(`自动加载了${autoGeneratedProducts.length}个1688一件代发商品`);