/**
 * search.js - Real-time product search functionality
 * Merges products from main.js (global 'products' array) and products_data.js (global 'autoGeneratedProducts' array)
 * Provides live search with debounce, highlighting, category display, and click-to-navigate.
 */

(function() {
    'use strict';

    // --- Constants ---
    var DEBOUNCE_DELAY = 300;
    var MAX_RESULTS_HEIGHT = 300;
    var NO_RESULTS_MSG = '\u672a\u627e\u5230\u5339\u914D\u7684\u4EA7\u54C1'; // "未找到匹配的产品"

    // --- DOM References ---
    var searchInput = document.getElementById('searchInput');
    var searchBtn = document.getElementById('searchBtn');
    var searchResults = document.getElementById('searchResults');

    // --- State ---
    var debounceTimer = null;

    /**
     * Escape special regex characters in a string.
     */
    function escapeRegExp(str) {
        return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    }

    /**
     * Highlight all occurrences of the search term within text.
     * Returns HTML string with <mark> tags around matches.
     */
    function highlightText(text, searchTerm) {
        if (!searchTerm || !text) return text || '';
        var escaped = escapeRegExp(searchTerm);
        var regex = new RegExp('(' + escaped + ')', 'gi');
        return text.replace(regex, '<mark class="search-highlight">$1</mark>');
    }

    /**
     * Normalize a product from either data source into a unified format.
     * Handles both 'products' array (id, name, price, category, description)
     * and 'autoGeneratedProducts' array (id, title, price, category, short_description).
     */
    function normalizeProduct(item) {
        var normalized = {
            id: item.id,
            name: item.name || item.title || '',
            price: item.price || 0,
            category: item.category || '',
            description: item.description || item.short_description || ''
        };

        // For auto-generated products, there's no images array; use a generic icon
        normalized.icon = item.icon || 'fas fa-tag';
        normalized.images = item.images || null;

        return normalized;
    }

    /**
     * Merge products from both global arrays into one deduplicated list.
     * products (from main.js) has priority; autoGeneratedProducts (from products_data.js) fills gaps.
     * Since products_data.js already merges into 'products' at runtime, we just use the products array,
     * but we also check autoGeneratedProducts separately in case it wasn't merged.
     */
    function getAllProducts() {
        var merged = [];

        // Get products from global 'products' array
        if (typeof products !== 'undefined' && Array.isArray(products)) {
            products.forEach(function(p) {
                merged.push(normalizeProduct(p));
            });
        }

        // Get products from global 'autoGeneratedProducts' array (if not already merged)
        if (typeof autoGeneratedProducts !== 'undefined' && Array.isArray(autoGeneratedProducts)) {
            var existingIds = {};
            merged.forEach(function(p) { existingIds[p.id] = true; });

            autoGeneratedProducts.forEach(function(p) {
                if (!existingIds[p.id]) {
                    merged.push(normalizeProduct(p));
                }
            });
        }

        return merged;
    }

    /**
     * Perform the actual search across all products.
     * Searches by name/title, category, and description/short_description.
     * Returns array of matching products.
     */
    function performSearch(query) {
        var searchTerm = query.trim().toLowerCase();
        if (searchTerm === '') {
            return [];
        }

        var allProducts = getAllProducts();
        var results = [];

        allProducts.forEach(function(product) {
            var name = (product.name || '').toLowerCase();
            var category = (product.category || '').toLowerCase();
            var description = (product.description || '').toLowerCase();

            if (name.indexOf(searchTerm) !== -1 ||
                category.indexOf(searchTerm) !== -1 ||
                description.indexOf(searchTerm) !== -1) {
                results.push(product);
            }
        });

        return results;
    }

    /**
     * Render the search results dropdown.
     */
    function renderResults(query, results) {
        if (!searchResults) return;

        var searchTerm = query.trim();

        if (results.length === 0 && searchTerm !== '') {
            searchResults.innerHTML = '<div class="no-results">' + NO_RESULTS_MSG + '</div>';
            searchResults.style.display = 'block';
            return;
        }

        if (results.length === 0) {
            searchResults.style.display = 'none';
            return;
        }

        var html = '';
        results.forEach(function(product) {
            var highlightedName = highlightText(product.name, searchTerm);
            var highlightedCategory = highlightText(product.category, searchTerm);
            var priceDisplay = '$' + Number(product.price).toFixed(2);

            // Build image if available
            var imageHtml = '';
            if (product.images && product.images.length > 0) {
                imageHtml = '<img src="' + product.images[0] + '" alt="' + escapeHtml(product.name) + '" loading="lazy" class="search-result-image">';
            } else {
                imageHtml = '<div class="search-result-image" style="width:40px;height:40px;display:flex;align-items:center;justify-content:center;background:#f3f4f6;border-radius:4px;"><i class="' + product.icon + '" style="color:#9ca3af;"></i></div>';
            }

            html += '<a href="product-detail.html?id=' + encodeURIComponent(product.id) + '" class="search-result-item">' +
                imageHtml +
                '<div class="search-result-info">' +
                    '<div class="search-result-name">' + highlightedName + '</div>' +
                    '<div class="search-result-price">' + priceDisplay + '</div>' +
                    '<span class="search-result-category">' + highlightedCategory + '</span>' +
                '</div>' +
            '</a>';
        });

        searchResults.innerHTML = html;
        searchResults.style.display = 'block';
    }

    /**
     * Simple HTML entity escape to prevent XSS.
     */
    function escapeHtml(str) {
        if (!str) return '';
        return String(str)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#039;');
    }

    /**
     * Execute the search: perform search + render results.
     */
    function executeSearch(query) {
        var results = performSearch(query);
        renderResults(query, results);
    }

    /**
     * Hide the search results dropdown.
     */
    function hideResults() {
        if (searchResults) {
            searchResults.style.display = 'none';
        }
    }

    // --- Event Listeners ---

    // 1. Input event with debounce (300ms)
    if (searchInput) {
        searchInput.addEventListener('input', function(e) {
            var query = e.target.value;
            clearTimeout(debounceTimer);
            debounceTimer = setTimeout(function() {
                executeSearch(query);
            }, DEBOUNCE_DELAY);
        });

        // 2. Click search button executes search immediately
        if (searchBtn) {
            searchBtn.addEventListener('click', function(e) {
                e.preventDefault();
                clearTimeout(debounceTimer);
                executeSearch(searchInput.value);
            });
        }

        // 3. Enter key in search input executes search immediately
        searchInput.addEventListener('keydown', function(e) {
            if (e.key === 'Enter') {
                e.preventDefault();
                clearTimeout(debounceTimer);
                executeSearch(searchInput.value);
            }
        });

        // 4. ESC key closes search results
        searchInput.addEventListener('keydown', function(e) {
            if (e.key === 'Escape') {
                hideResults();
                searchInput.blur();
            }
        });
    }

    // 5. Click outside search container closes results
    document.addEventListener('click', function(e) {
        var searchContainer = document.querySelector('.search-container');
        if (searchContainer && !searchContainer.contains(e.target)) {
            hideResults();
        }
    });

    // 6. Click on a search result closes the dropdown (handled by the <a> tag navigating away,
    //    but if clicked via some other mechanism, still hide)
    if (searchResults) {
        searchResults.addEventListener('click', function(e) {
            // Allow clicks on <a> links to propagate normally (navigation)
            // But hide the results panel after a short delay to avoid flash
            var target = e.target.closest('.search-result-item');
            if (target) {
                // The default link navigation will happen
                setTimeout(hideResults, 100);
            }
        });
    }

    // --- Expose public API ---

    /**
     * Public API: window.searchProducts(query)
     * Allows other scripts to programmatically search products.
     * Returns array of matched product objects.
     *
     * @param {string} query - Search keyword(s)
     * @returns {Array} Array of matched products
     */
    window.searchProducts = function(query) {
        if (typeof query !== 'string') return [];
        return performSearch(query);
    };

    console.log('search.js loaded - Real-time search initialized');

})();
