// Wishlist / Favorites System
(function() {
    'use strict';

    const STORAGE_KEY = 'shopEasyWishlist';

    // Get wishlist data from localStorage
    function getData() {
        try {
            const data = localStorage.getItem(STORAGE_KEY);
            return data ? JSON.parse(data) : { items: [] };
        } catch (e) {
            return { items: [] };
        }
    }

    // Save wishlist data to localStorage
    function saveData(data) {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    }

    // Check if a product is wishlisted
    function isWishlisted(productId) {
        const data = getData();
        return data.items.indexOf(productId) !== -1;
    }

    // Add product to wishlist
    function add(productId) {
        const data = getData();
        if (data.items.indexOf(productId) === -1) {
            data.items.push(productId);
            saveData(data);
            updateUI();
            showNotification(productId, 'added');
            animateHeart(productId);
        }
        return data.items;
    }

    // Remove product from wishlist
    function remove(productId) {
        const data = getData();
        const index = data.items.indexOf(productId);
        if (index !== -1) {
            data.items.splice(index, 1);
            saveData(data);
            updateUI();
            showNotification(productId, 'removed');
        }
        return data.items;
    }

    // Toggle wishlist status
    function toggle(productId) {
        if (isWishlisted(productId)) {
            remove(productId);
        } else {
            add(productId);
        }
        return isWishlisted(productId);
    }

    // Get all wishlisted product IDs
    function getAll() {
        const data = getData();
        return data.items;
    }

    // Get full product info for all wishlisted items (merging products and autoGeneratedProducts)
    function getProducts() {
        const ids = getAll();
        if (ids.length === 0) return [];

        // Combine products from both sources
        let allProducts = [];

        if (typeof window.products !== 'undefined' && Array.isArray(window.products)) {
            allProducts = allProducts.concat(window.products);
        }
        if (typeof window.autoGeneratedProducts !== 'undefined' && Array.isArray(window.autoGeneratedProducts)) {
            allProducts = allProducts.concat(window.autoGeneratedProducts);
        }

        return ids.map(id => allProducts.find(p => p.id === id)).filter(p => p !== undefined);
    }

    // Get wishlist count
    function getCount() {
        const data = getData();
        return data.items.length;
    }

    // Show notification
    function showNotification(productId, action) {
        var productName = '';
        // Try to get product name
        if (typeof window.products !== 'undefined') {
            var p = window.products.find(function(pr) { return pr.id === productId; });
            if (p) productName = p.name;
        }
        if (!productName && typeof window.autoGeneratedProducts !== 'undefined') {
            var p = window.autoGeneratedProducts.find(function(pr) { return pr.id === productId; });
            if (p) productName = p.name;
        }

        var message = action === 'added'
            ? (productName ? '"' + productName + '" added to wishlist' : 'Added to wishlist')
            : (productName ? '"' + productName + '" removed from wishlist' : 'Removed from wishlist');

        var notification = document.createElement('div');
        notification.className = 'notification wishlist-notification';
        var iconClass = action === 'added' ? 'fa-heart' : 'fa-heart-broken';
        notification.innerHTML = '<i class="fas ' + iconClass + '"></i> <span>' + message + '</span> <button class="notification-close">&times;</button>';

        document.body.appendChild(notification);

        // Close button
        notification.querySelector('.notification-close').addEventListener('click', function() {
            notification.remove();
        });

        // Auto remove after 3 seconds
        setTimeout(function() {
            if (notification.parentNode) {
                notification.style.animation = 'slideOut 0.3s ease forwards';
                setTimeout(function() {
                    if (notification.parentNode) notification.remove();
                }, 300);
            }
        }, 2500);
    }

    // Animate heart icon
    function animateHeart(productId) {
        var buttons = document.querySelectorAll('.btn-wishlist[data-id="' + productId + '"]');
        buttons.forEach(function(btn) {
            var icon = btn.querySelector('i');
            if (icon) {
                icon.classList.add('wishlist-bounce');
                setTimeout(function() {
                    icon.classList.remove('wishlist-bounce');
                }, 600);
            }
        });
    }

    // Update all wishlist buttons and badge
    function updateUI() {
        var count = getCount();

        // Update all .btn-wishlist buttons
        document.querySelectorAll('.btn-wishlist').forEach(function(btn) {
            var id = parseInt(btn.getAttribute('data-id'));
            if (!id) {
                // Try to get from parent context or URL for detail page
                var params = new URLSearchParams(window.location.search);
                var urlId = parseInt(params.get('id'));
                if (urlId && btn.closest('.product-detail-section')) {
                    id = urlId;
                }
            }
            if (id) {
                var isFav = isWishlisted(id);
                var icon = btn.querySelector('i');
                if (icon) {
                    if (isFav) {
                        icon.className = 'fas fa-heart';
                        btn.classList.add('wishlisted');
                    } else {
                        icon.className = 'far fa-heart';
                        btn.classList.remove('wishlisted');
                    }
                }
                var textSpan = btn.querySelector('span') || btn.childNodes[btn.childNodes.length - 1];
                // Update text if present (for detail page)
                if (btn.innerHTML.indexOf('Wishlist') !== -1 || btn.innerHTML.indexOf('收藏') !== -1) {
                    if (isFav) {
                        btn.innerHTML = btn.innerHTML.replace(/far fa-heart/g, 'fas fa-heart');
                        btn.innerHTML = btn.innerHTML.replace(/Add to Wishlist/g, 'In Wishlist');
                        btn.innerHTML = btn.innerHTML.replace(/加入收藏/g, '已收藏');
                    } else {
                        btn.innerHTML = btn.innerHTML.replace(/fas fa-heart/g, 'far fa-heart');
                        btn.innerHTML = btn.innerHTML.replace(/In Wishlist/g, 'Add to Wishlist');
                        btn.innerHTML = btn.innerHTML.replace(/已收藏/g, '加入收藏');
                    }
                }
            }
        });

        // Update badge in navbar
        var badge = document.querySelector('.wishlist-count');
        if (badge) {
            badge.textContent = count;
            badge.style.display = count > 0 ? 'flex' : 'none';
        }

        // Update wishlist page count display if on wishlist page
        var countDisplay = document.getElementById('wishlist-count-display');
        if (countDisplay) {
            countDisplay.textContent = count;
        }
    }

    // Bind wishlist buttons
    function bindButtons() {
        document.addEventListener('click', function(e) {
            var btn = e.target.closest('.btn-wishlist');
            if (btn) {
                e.preventDefault();
                var id = parseInt(btn.getAttribute('data-id'));
                if (!id) {
                    // For product detail page, get from URL
                    var params = new URLSearchParams(window.location.search);
                    id = parseInt(params.get('id'));
                }
                if (id) {
                    toggle(id);
                }
            }
        });
    }

    // Initialize
    function init() {
        bindButtons();
        updateUI();

        // Re-run updateUI when products_data.js loads
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', updateUI);
        } else {
            updateUI();
        }
    }

    // Expose global API
    window.wishlist = {
        add: add,
        remove: remove,
        toggle: toggle,
        isWishlisted: isWishlisted,
        getAll: getAll,
        getProducts: getProducts,
        get count() { return getCount(); }
    };

    // Run
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }
})();
